replicas: 3

namespace: default

image:
  repo: chaudharishubham2911/argocd-demo
  tag: 07fdc324161da8bc7142b6700b9c59300eee8af0
  pullPolicy: Always

port: 9090

labels:
  app: myapp
  environment: dev
  tier: backend

service:
  type: NodePort

rollout:
  revisionHistoryLimit: 3
