replicas: 3

namespace: default

image:
  repo: chaudharishubham2911/argocd-demo
  tag: 73b14a92a939e87ea0171240255af264bd258951
  pullPolicy: Always

port: 9090

labels:
  app: myapp
  environment: dev
  tier: backend

service:
  type: NodePort

rollout:
  revisionHistoryLimit: 3
