replicas: 3

namespace: default

image:
  repo: chaudharishubham2911/argocd-demo
  tag: 27
  pullPolicy: Always

port: 9090

labels:
  app: myapp
  environment: dev
  tier: backend

service:
  type: NodePort

rollout:
  revisionHistoryLimit: 3
