---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: myapp-secret
spec:
  encryptedData:
    password: AgCU5kq9tWpmmtOE9jc0YBF22ivXF5UXWcLFz9KyqSjfcxAaLuXpRGGF/bNpZNcS2iOzbLnYp739qxi5cMhyIDNP4y9y8zuQi5+zP4+U/6ZHBxzdBBJjF9z4CksXZ6JKgqfBoR0ZGL8QQIGw4yvCnj8Wu8WmLFt4Pvdm0jdqjrbDX2iKxc36O/XRT+rX/8IuyiyKtQHSG60eKjqmDElwQWwErY1It1EclcgqTDn0/+G0TW7FHBNhLMFa5uq+Et00y6kOewGHPKv3V1YM5KsUrIjM9QeankcOR5cmZA8MsmnowzQf4xYQRo0MSB3IYLPPv6LefeOt60t2w1rCXRYhS2zumPVNLpxBBgafdyvVXUWql7m7M0QOsw4h0InPxNOwEOl+hu7r38CqRThvI6Ti3BZC1wBrUishA6VRCQnkrq0Kp8yuQZSGhMOrsIWnwXi5d4mEYezHifF5ndZYp1S+xSAkW7BnthImr44tJ9N65bNELYiTWthRft6KxIBWmWJgVNTPS5/bJg8HaRm50ynpuKyeDGytHL4BdrqZNsKqdTrJ54GuZ2K/mcTqdzBD5vxNf/c1RyHCQWJqRu00TQrXXDPt5ynCKIrBSiL2/9ZRR644fxlxq/o3Sr29Xk6z+XDzBHiQMPjuWGa+wKXLrFCP8Ra2fO8V0/sIYyT+lv/rVmV968r9dYigzLGSZ8+DC3sWWpxu5GPGr57pFg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: myapp-secret
    type: Opaque