apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.labels.app }}
  labels:
      {{- with .Values.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.port }}
    name: http
  selector:
      {{- with .Values.labels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}